from enum import Enum

class DataType(Enum):
    FINANCIAL_DATA_AE = "FINANCIAL_DATA_AE"
    FINANCIAL_DATA_CP = "FINANCIAL_DATA_CP"
    FRANCE_RELANCE = "FRANCE_RELANCE"
    REFERENTIEL = "REFERENTIEL"
