"""empty message

Revision ID: 0af544930fc5
Revises: eab12c622c57
Create Date: 2022-09-29 11:59:57.935283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af544930fc5'
down_revision = 'eab12c622c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ref_code_programme', sa.Column('theme', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ref_code_programme', 'ref_theme', ['theme'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ref_code_programme', type_='foreignkey')
    op.drop_column('ref_code_programme', 'theme')
    op.drop_table('ref_theme')
    # ### end Alembic commands ###
