"""empty message

Revision ID: 2deb826b5cdb
Revises: 99811ad2865a
Create Date: 2022-10-03 15:11:58.280170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy import Column, String

# revision identifiers, used by Alembic.
revision = '20221004_ref_cat_juridique'
down_revision = '20221003_ref_commune'
branch_labels = None
depends_on = None

class _Base(orm.DeclarativeBase):
    pass
class _CategorieJuridique(_Base):
    __tablename__ = 'ref_categorie_juridique'
    id = sa.Column(sa.Integer, primary_key=True)
    code: str = Column(String, unique=True, nullable=False)
    type: str = Column(String)
    label: str = Column(String)


categorieJuridique = {"0000": "Collectivité",
                      "1000": "",
                      "2110": "",
                      "2120": "",
                      "2210": "Entreprise",
                      "2220": "Entreprise",
                      "2310": "Entreprise",
                      "2320": "Entreprise",
                      "2385": "Entreprise",
                      "2400": "",
                      "2700": "",
                      "2900": "",
                      "3110": "",
                      "3120": "Entreprise",
                      "3205": "Collectivité",
                      "3210": "Etat",
                      "3220": "Entreprise",
                      "3290": "Entreprise",
                      "4110": "Etat",
                      "4120": "Etat",
                      "4130": "Collectivité",
                      "4140": "Collectivité",
                      "4150": "Collectivité",
                      "4160": "Collectivité",
                      "5191": "Entreprise",
                      "5192": "Entreprise",
                      "5193": "Entreprise",
                      "5194": "Entreprise",
                      "5195": "Entreprise",
                      "5196": "Entreprise",
                      "5202": "Entreprise",
                      "5203": "Entreprise",
                      "5306": "Entreprise",
                      "5307": "Entreprise",
                      "5308": "Entreprise",
                      "5309": "Entreprise",
                      "5310": "Entreprise",
                      "5370": "Entreprise",
                      "5385": "Entreprise",
                      "5410": "Entreprise",
                      "5415": "Entreprise",
                      "5422": "Entreprise",
                      "5426": "Entreprise",
                      "5430": "Entreprise",
                      "5431": "Entreprise",
                      "5432": "Entreprise",
                      "5442": "Entreprise",
                      "5443": "Entreprise",
                      "5451": "Entreprise",
                      "5453": "Entreprise",
                      "5454": "Entreprise",
                      "5455": "Entreprise",
                      "5458": "Entreprise",
                      "5459": "Entreprise",
                      "5460": "Entreprise",
                      "5470": "Entreprise",
                      "5485": "Entreprise",
                      "5499": "Entreprise",
                      "5500": "Entreprise",
                      "5505": "Entreprise",
                      "5510": "Entreprise",
                      "5515": "Entreprise",
                      "5520": "Entreprise",
                      "5522": "Entreprise",
                      "5525": "Entreprise",
                      "5530": "Entreprise",
                      "5531": "Entreprise",
                      "5532": "Entreprise",
                      "5542": "Entreprise",
                      "5543": "Entreprise",
                      "5546": "Entreprise",
                      "5547": "Entreprise",
                      "5548": "Entreprise",
                      "5551": "Entreprise",
                      "5552": "Entreprise",
                      "5553": "Entreprise",
                      "5554": "Entreprise",
                      "5555": "Entreprise",
                      "5558": "Entreprise",
                      "5559": "Entreprise",
                      "5560": "Entreprise",
                      "5570": "Entreprise",
                      "5585": "Entreprise",
                      "5599": "Entreprise",
                      "5605": "Entreprise",
                      "5610": "Entreprise",
                      "5615": "Entreprise",
                      "5620": "Entreprise",
                      "5622": "Entreprise",
                      "5625": "Entreprise",
                      "5630": "Entreprise",
                      "5631": "Entreprise",
                      "5632": "Entreprise",
                      "5642": "Entreprise",
                      "5643": "Entreprise",
                      "5646": "Entreprise",
                      "5647": "Entreprise",
                      "5648": "Entreprise",
                      "5651": "Entreprise",
                      "5652": "Entreprise",
                      "5653": "Entreprise",
                      "5654": "Entreprise",
                      "5655": "Entreprise",
                      "5658": "Entreprise",
                      "5659": "Entreprise",
                      "5660": "Entreprise",
                      "5670": "Entreprise",
                      "5685": "Entreprise",
                      "5699": "Entreprise",
                      "5710": "Entreprise",
                      "5770": "Entreprise",
                      "5785": "Entreprise",
                      "5800": "Entreprise",
                      "6100": "Entreprise",
                      "6210": "Entreprise",
                      "6220": "Entreprise",
                      "6316": "Entreprise",
                      "6317": "Entreprise",
                      "6318": "Entreprise",
                      "6411": "Entreprise",
                      "6511": "Entreprise",
                      "6521": "Entreprise",
                      "6532": "Entreprise",
                      "6533": "Entreprise",
                      "6534": "Entreprise",
                      "6535": "Entreprise",
                      "6536": "Entreprise",
                      "6537": "Entreprise",
                      "6538": "Entreprise",
                      "6539": "Entreprise",
                      "6540": "Entreprise",
                      "6541": "Entreprise",
                      "6542": "Entreprise",
                      "6543": "Entreprise",
                      "6544": "Entreprise",
                      "6551": "Entreprise",
                      "6554": "Entreprise",
                      "6558": "Entreprise",
                      "6560": "Entreprise",
                      "6561": "Entreprise",
                      "6562": "Entreprise",
                      "6563": "Entreprise",
                      "6564": "Entreprise",
                      "6565": "Entreprise",
                      "6566": "Entreprise",
                      "6567": "Entreprise",
                      "6568": "Entreprise",
                      "6569": "Entreprise",
                      "6571": "Entreprise",
                      "6572": "Entreprise",
                      "6573": "Entreprise",
                      "6574": "Entreprise",
                      "6575": "Entreprise",
                      "6576": "Entreprise",
                      "6577": "Entreprise",
                      "6578": "Entreprise",
                      "6585": "Entreprise",
                      "6589": "Entreprise",
                      "6595": "Entreprise",
                      "6596": "Entreprise",
                      "6597": "Entreprise",
                      "6598": "Entreprise",
                      "6599": "Entreprise",
                      "6901": "Entreprise",
                      "7111": "Etat",
                      "7112": "Etat",
                      "7113": "Etat",
                      "7120": "Etat",
                      "7150": "Etat",
                      "7160": "Etat",
                      "7171": "Etat",
                      "7172": "Etat",
                      "7179": "Etat",
                      "7190": "Etat",
                      "7210": "Collectivité",
                      "7220": "Collectivité",
                      "7225": "Collectivité",
                      "7229": "Collectivité",
                      "7230": "Collectivité",
                      "7312": "Collectivité",
                      "7313": "Collectivité",
                      "7314": "Collectivité",
                      "7321": "Collectivité",
                      "7322": "Collectivité",
                      "7323": "Collectivité",
                      "7331": "Collectivité",
                      "7340": "Collectivité",
                      "7341": "Collectivité",
                      "7342": "Collectivité",
                      "7343": "Collectivité",
                      "7344": "Collectivité",
                      "7345": "Collectivité",
                      "7346": "Collectivité",
                      "7347": "Collectivité",
                      "7348": "Collectivité",
                      "7349": "Collectivité",
                      "7510":"Collectivité",
                      "7351": "",
                      "7352": "",
                      "7353": "",
                      "7354": "",
                      "7355": "",
                      "7356": "",
                      "7357": "",
                      "7361": "",
                      "7362": "",
                      "7363": "",
                      "7364": "",
                      "7365": "",
                      "7366": "",
                      "7367": "",
                      "7371": "",
                      "7372": "",
                      "7373": "",
                      "7378": "",
                      "7379": "",
                      "7381": "",
                      "7382": "",
                      "7383": "",
                      "7384": "",
                      "7385": "",
                      "7389": "",
                      "7410": "",
                      "7430": "",
                      "7450": "",
                      "7470": "",
                      "7490": "",
                      "8110": "",
                      "8120": "",
                      "8130": "",
                      "8140": "",
                      "8150": "",
                      "8160": "",
                      "8170": "",
                      "8190": "",
                      "8210": "",
                      "8250": "",
                      "8290": "",
                      "8310": "",
                      "8311": "",
                      "8410": "",
                      "8420": "",
                      "8450": "",
                      "8470": "",
                      "8490": "",
                      "8510": "",
                      "8520": "",
                      "9110": "Association",
                      "9150": "Association",
                      "9210": "Association",
                      "9220": "Association",
                      "9221": "Association",
                      "9222": "Association",
                      "9223": "Association",
                      "9224": "Association",
                      "9230": "Association",
                      "9240": "",
                      "9260": "Association",
                      "9300": "",
                      "9900": "",
                      "9970": ""}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_categorie_juridique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )

    session = orm.Session(bind=op.get_bind())

    # insert data
    for code in categorieJuridique :
        categorie = _CategorieJuridique(code = code, type = None if categorieJuridique[code] == "" else categorieJuridique[code] )
        session.add(categorie)
        session.commit()

    op.create_foreign_key(None, 'ref_siret', 'ref_categorie_juridique', ['categorie_juridique'], ['code'])


    # ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ref_siret_categorie_juridique_fkey', 'ref_siret', type_='foreignkey')
    op.drop_table('ref_categorie_juridique')
    ### end Alembic commands ###
