"""fix idempotence ademe et cp

Revision ID: f40aeeb60300
Revises: 20230607_ademe
Create Date: 2023-06-20 10:22:07.678673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40aeeb60300'
down_revision = '20230607_ademe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ademe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_import_taskid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_import_lineno', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_file_line_import_ademe', ['file_import_taskid', 'file_import_lineno'])
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_cp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_import_taskid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_import_lineno', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_file_line_import_cp', ['file_import_taskid', 'file_import_lineno'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ademe', schema=None) as batch_op:
        batch_op.drop_constraint('uq_file_line_import_ademe', type_='unique')
        batch_op.drop_column('file_import_lineno')
        batch_op.drop_column('file_import_taskid')
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_cp', schema=None) as batch_op:
        batch_op.drop_constraint('uq_file_line_import_cp', type_='unique')
        batch_op.drop_column('file_import_lineno')
        batch_op.drop_column('file_import_taskid')
    # ### end Alembic commands ###