"""empty message

Revision ID: 13945f856f25
Revises: 20230517_loc_interminis
Create Date: 2023-05-19 17:44:05.969502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20230519_montant_ae'
down_revision = '20230517_loc_interminis'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('montant_financial_ae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_financial_ae', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_financial_ae'], ['financial_ae.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # TODO Faire migration des montants

    with op.batch_alter_table('financial_ae', schema=None) as batch_op:
        batch_op.drop_column('montant')



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ref_siret', schema=None) as batch_op:
        batch_op.alter_column('code_commune',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('financial_ae', schema=None) as batch_op:
        batch_op.add_column(sa.Column('montant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('unique_ej_poste_ej', ['n_ej', 'n_poste_ej'])

    op.create_table('nc_evolutions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('titleDown', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('batch', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nc_evolutions_pkey')
    )
    op.drop_table('montant_financial_ae')
    # ### end Alembic commands ###
