"""empty message

Revision ID: db4694852b72
Revises: 20230208_pref_and_region
Create Date: 2023-03-15 10:07:41.229139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '20230316_annee_chorus'
down_revision = '20230208_pref_and_region'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_chorus', sa.Column('annee', sa.Integer(), nullable=False, server_default=text('0')))
    op.add_column('data_chorus', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('data_chorus', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_chorus', 'updated_at')
    op.drop_column('data_chorus', 'created_at')
    op.drop_column('data_chorus', 'annee')
    # ### end Alembic commands ###
