"""empty message

Revision ID: 227faf0e83ff
Revises: 20230417_financial_cp
Create Date: 2023-05-17 09:28:37.050565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20230517_loc_interminis'
down_revision = '20230417_financial_cp'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('ref_localisation_interministerielle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commune_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ref_commune', ['commune_id'], ['id'])
        batch_op.drop_column('commune')
        batch_op.drop_column('code_departement')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('ref_localisation_interministerielle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_departement', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commune', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('commune_id')
    # ### end Alembic commands ###
