"""empty message

Revision ID: 3d421e0269d7
Revises: 20230113_preference
Create Date: 2023-02-01 17:15:58.631234

"""
import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm


# revision identifiers, used by Alembic.
revision = '20230201_audit_preference'
down_revision = '20230113_preference'
branch_labels = None
depends_on = None


def upgrade():
    query_column_date_creation = "ALTER TABLE settings.preference_users ADD COLUMN date_creation timestamptz DEFAULT CURRENT_TIMESTAMP"
    query_column_dernier_acces = "ALTER TABLE settings.preference_users ADD COLUMN dernier_acces timestamptz DEFAULT NULL"
    query_column_nombre_utilisation = "ALTER TABLE settings.preference_users ADD COLUMN nombre_utilisation INTEGER DEFAULT 0"
    query_column_email_send = "ALTER TABLE settings.share_preference ADD COLUMN email_send BOOLEAN DEFAULT False"

    op.execute(query_column_date_creation)
    op.execute(query_column_dernier_acces)
    op.execute(query_column_nombre_utilisation)
    op.execute(query_column_email_send)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    query_column_date_creation = "ALTER TABLE settings.preference_users DROP COLUMN date_creation "
    query_column_dernier_acces = "ALTER TABLE settings.preference_users DROP COLUMN dernier_acces "
    query_column_nombre_utilisation = "ALTER TABLE settings.preference_users DROP COLUMN nombre_utilisation "
    query_column_email_send = "ALTER TABLE settings.share_preference DROP COLUMN email_send "

    op.execute(query_column_date_creation)
    op.execute(query_column_dernier_acces)
    op.execute(query_column_nombre_utilisation)
    op.execute(query_column_email_send)
