"""empty message

Revision ID: a4e1210b7130
Revises: 20230316_annee_chorus
Create Date: 2023-03-17 17:00:22.038372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e1210b7130'
down_revision = '20230316_annee_chorus'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # REF MINISTERE
    op.create_table('ref_ministere',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('sigle_ministere', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # DROP Compte generale
    op.drop_constraint('data_chorus_compte_general_fkey', 'data_chorus', type_='foreignkey')
    op.drop_column('data_chorus', 'compte_general')
    op.drop_table('ref_compte_general')

    #UPDATE CENTRE COUTS
    op.add_column('ref_centre_couts', sa.Column('code_postal', sa.String(), nullable=True))
    op.add_column('ref_centre_couts', sa.Column('ville', sa.String(), nullable=True))
    op.add_column('ref_code_programme', sa.Column('code_ministere', sa.String(), nullable=True))

    # ADD FK MINISTERE TO CODE PROGRAMME
    op.create_foreign_key('ref_code_programme_ref_ministere_fkey', 'ref_code_programme', 'ref_ministere', ['code_ministere'], ['code'])

    #UPDATE groupe marchandise
    op.add_column('ref_groupe_marchandise', sa.Column('code_pce', sa.String(), nullable=True))
    op.add_column('ref_groupe_marchandise', sa.Column('label_pce', sa.String(), nullable=True))

    #UPDATE localisation interministerielle
    op.add_column('ref_localisation_interministerielle', sa.Column('code_departement', sa.String(), nullable=True))
    op.add_column('ref_localisation_interministerielle', sa.Column('commune', sa.String(), nullable=True))
    op.add_column('ref_localisation_interministerielle', sa.Column('site', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('ref_localisation_interministerielle', 'site')
    op.drop_column('ref_localisation_interministerielle', 'commune')
    op.drop_column('ref_localisation_interministerielle', 'code_departement')

    op.drop_column('ref_groupe_marchandise', 'label_pce')
    op.drop_column('ref_groupe_marchandise', 'code_pce')

    op.drop_column('ref_code_programme', 'code_ministere')
    op.drop_column('ref_centre_couts', 'ville')
    op.drop_column('ref_centre_couts', 'code_postal')

    op.create_table('ref_compte_general',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ref_compte_general_pkey'),
    sa.UniqueConstraint('code', name='ref_compte_general_code_key')
    )

    op.add_column('data_chorus', sa.Column('compte_general', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('data_chorus_compte_general_fkey', 'data_chorus', 'ref_compte_general', ['compte_general'],
                          ['code'])

    op.drop_table('ref_region')
    op.drop_table('ref_ministere')
    # ### end Alembic commands ###
