"""ademe_from_datagouv

Revision ID: d1a470f3416f
Revises: f40aeeb60300
Create Date: 2023-07-06 17:42:59.052516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a470f3416f'
down_revision = 'f40aeeb60300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ademe', schema=None) as batch_op:
        batch_op.drop_column('location_lat')
        batch_op.drop_column('departement')
        batch_op.drop_column('location_lon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ademe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departement', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
