DEBUG: true

SQLALCHEMY_DATABASE_URI : "postgresql://postgres:password@localhost:5432/CHORUS"


CELERY_BROKER_URL: 'redis://localhost:6379/1'
result_backend: "postgresql://postgres:password@localhost:5432/tasks"

api_siren : http://152.228.212.208:443/v3/etablissements/

UPLOAD_FOLDER: "c:\\toWatch"

NOCODB_URL : "<url>"

TOKEN_NOCO_DB :
  PROJET-NOCO : "<TOKEN>"
