DEBUG: true

 # Connexion à la BDD principal de Chorus
SQLALCHEMY_DATABASE_URI : "postgresql+psycopg://postgres:password@localhost:5432/<DBNAME>"

 # préciser les connections au BDD d'audit et de settings
SQLALCHEMY_BINDS:
  audit: #schema audit
    url: "postgresql+psycopg://postgres:password@localhost:5432/<DBNAME>?options=-c%20search_path=audit"
    pool_pre_ping: True
    pool_recycle: 30
  settings:  #schema audit
    url: "postgresql+psycopg://postgres:password@localhost:5432/<DBNAME>?options=-c%20search_path=settings"
    pool_pre_ping: True
    pool_recycle: 30

SQLALCHEMY_ENGINE_OPTIONS:
  pool_pre_ping: True
  pool_recycle: 30

#CONFIG CELERY REDIS
CELERY_BROKER_URL: 'redis://localhost:6379/1'
result_backend : "db+postgresql+psycopg://postgres:password@localhost:5432/<DBNAME_TASK>"
result_extended: True
task_track_started : True
max_queue_size: 100 # nombre de message max en attente dans une file redis
timeout_queue_retry: 60

# SECRET KEY OIDC Keycloak
SECRET_KEY: "OIDC"

# Checmin de stockage des fichiers uploader
UPLOAD_FOLDER: "<PATH_FOLDER>"


# CONFIGURATION OPENID Keycloak pour la securation des endpoints
KEYCLOAK_OPENID:
  URL: <url>
  SECRET_KEY: "<secret key>"
  REALM: <realm>
  CLIENT_ID: "client_id"


# CONFIGURATION pour keycloak ADMIN (gestion des utilisateurs)
KEYCLOAK_ADMIN:
  URL: <url>
  SECRET_KEY: "<secret key>"
  REALM: <realm>

ERROR_INCLUDE_MESSAGE: False

# CONFIGURATION Pour l'api Entreprise api.gouv.fr
# En example l'api de staging
API_ENTREPRISE:
  URL: https://staging.entreprise.api.gouv.fr
  TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI1MmE1YmZjMi1jMzUwLTQ4ZjQtYjY5Ni05ZWE3NmRiM2VmMjkiLCJqdGkiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJzY29wZXMiOlsiY2VydGlmaWNhdF9yZ2VfYWRlbWUiLCJtc2FfY290aXNhdGlvbnMiLCJlbnRyZXByaXNlcyIsImV4dHJhaXRzX3JjcyIsImNlcnRpZmljYXRfb3BxaWJpIiwiYXNzb2NpYXRpb25zIiwiZXRhYmxpc3NlbWVudHMiLCJmbnRwX2NhcnRlX3BybyIsInF1YWxpYmF0IiwiZW50cmVwcmlzZXNfYXJ0aXNhbmFsZXMiLCJjZXJ0aWZpY2F0X2NuZXRwIiwiZW9yaV9kb3VhbmVzIiwicHJvYnRwIiwiYWN0ZXNfaW5waSIsImV4dHJhaXRfY291cnRfaW5waSIsImF0dGVzdGF0aW9uc19zb2NpYWxlcyIsImxpYXNzZV9maXNjYWxlIiwiYXR0ZXN0YXRpb25zX2Zpc2NhbGVzIiwiZXhlcmNpY2VzIiwiY29udmVudGlvbnNfY29sbGVjdGl2ZXMiLCJiaWxhbnNfaW5waSIsImRvY3VtZW50c19hc3NvY2lhdGlvbiIsImNlcnRpZmljYXRfYWdlbmNlX2JpbyIsImJpbGFuc19lbnRyZXByaXNlX2JkZiIsImF0dGVzdGF0aW9uc19hZ2VmaXBoIiwibWVzcmlfaWRlbnRpZmlhbnQiLCJtZXNyaV9pZGVudGl0ZSIsIm1lc3JpX2luc2NyaXB0aW9uX2V0dWRpYW50IiwibWVzcmlfaW5zY3JpcHRpb25fYXV0cmUiLCJtZXNyaV9hZG1pc3Npb24iLCJtZXNyaV9ldGFibGlzc2VtZW50cyIsInBvbGVfZW1wbG9pX2lkZW50aXRlIiwicG9sZV9lbXBsb2lfYWRyZXNzZSIsInBvbGVfZW1wbG9pX2NvbnRhY3QiLCJwb2xlX2VtcGxvaV9pbnNjcmlwdGlvbiIsImNuYWZfcXVvdGllbnRfZmFtaWxpYWwiLCJjbmFmX2FsbG9jYXRhaXJlcyIsImNuYWZfZW5mYW50cyIsImNuYWZfYWRyZXNzZSIsImNub3VzX3N0YXR1dF9ib3Vyc2llciIsInVwdGltZSIsImNub3VzX2VjaGVsb25fYm91cnNlIiwiY25vdXNfZW1haWwiLCJjbm91c19wZXJpb2RlX3ZlcnNlbWVudCIsImNub3VzX3N0YXR1dF9ib3Vyc2UiLCJjbm91c192aWxsZV9ldHVkZXMiLCJjbm91c19pZGVudGl0ZSIsImRnZmlwX2RlY2xhcmFudDFfbm9tIiwiZGdmaXBfZGVjbGFyYW50MV9ub21fbmFpc3NhbmNlIiwiZGdmaXBfZGVjbGFyYW50MV9wcmVub21zIiwiZGdmaXBfZGVjbGFyYW50MV9kYXRlX25haXNzYW5jZSIsImRnZmlwX2RlY2xhcmFudDJfbm9tIiwiZGdmaXBfZGVjbGFyYW50Ml9ub21fbmFpc3NhbmNlIiwiZGdmaXBfZGVjbGFyYW50Ml9wcmVub21zIiwiZGdmaXBfZGVjbGFyYW50Ml9kYXRlX25haXNzYW5jZSIsImRnZmlwX2RhdGVfcmVjb3V2cmVtZW50IiwiZGdmaXBfZGF0ZV9ldGFibGlzc2VtZW50IiwiZGdmaXBfYWRyZXNzZV9maXNjYWxlX3RheGF0aW9uIiwiZGdmaXBfYWRyZXNzZV9maXNjYWxlX2FubmVlIiwiZGdmaXBfbm9tYnJlX3BhcnRzIiwiZGdmaXBfbm9tYnJlX3BlcnNvbm5lc19hX2NoYXJnZSIsImRnZmlwX3NpdHVhdGlvbl9mYW1pbGlhbGUiLCJkZ2ZpcF9yZXZlbnVfYnJ1dF9nbG9iYWwiLCJkZ2ZpcF9yZXZlbnVfaW1wb3NhYmxlIiwiZGdmaXBfaW1wb3RfcmV2ZW51X25ldF9hdmFudF9jb3JyZWN0aW9ucyIsImRnZmlwX21vbnRhbnRfaW1wb3QiLCJkZ2ZpcF9yZXZlbnVfZmlzY2FsX3JlZmVyZW5jZSIsImRnZmlwX2FubmVlX2ltcG90IiwiZGdmaXBfYW5uZWVfcmV2ZW51cyIsImRnZmlwX2VycmV1cl9jb3JyZWN0aWYiLCJkZ2ZpcF9zaXR1YXRpb25fcGFydGllbGxlIl0sInN1YiI6InN0YWdpbmcgZGV2ZWxvcG1lbnQiLCJpYXQiOjE2NjY4NjQwNzQsInZlcnNpb24iOiIxLjAiLCJleHAiOjE5ODI0ODMyNzR9.u2kMWzll3iCTczUOqMQbpS66VfrVzI2lLiyGEPcKAec
  CONTEXT: <CONTEXTE>
  RECIPIENT: <RECIPIENT> # siret du sib
  OBJECT: <OBJECT>

  # CONFIGURATION POUR LIMITER les appels à l'api Entreprise
  RATELIMITER:
    # Exemple 50 appel toutes les 70 secondes
    LIMIT: 50
    DURATION: 70
    # Stockage du lock
    REDIS:
      HOST: localhost
      PORT: 6379
      DB: 0

# URL vers API DATA Subventions
API_DATA_SUBVENTIONS:
  URL: <DS_URL>
  TOKEN: <DS_TOKEN>

API_DEMARCHE_SIMPLIFIE:
  URL: DMS_URL
  TOKEN: TOKEN

# COnfiguration SMTP pour envoi de mail
SMTP:
  server: ""
  port: 465
  from_email: ""
  pwd: "password"
  use_ssl: True

#  CONFIGURATION de Nocodb
NOCODB_URL : "<url>"
NOCODB_PROJECT:
   # Lister ici les projet et les token associés aux projets
  PROJECT: TOKEN_API
  PROJECT_2: TOKEN_API_PROJECT
