DEBUG: true

SQLALCHEMY_DATABASE_URI : "postgresql://postgres:password@localhost:5432/CHORUS"


CELERY_BROKER_URL: 'redis://localhost:6379/1'
result_backend: "postgresql://postgres:password@localhost:5432/tasks"

SECRET_KEY: "OIDC"

api_siren : http://152.228.212.208:443/v3/etablissements/

UPLOAD_FOLDER: "c:\\toWatch"


KEYCLOAK_ADMIN_URL: "url"
KEYCLOAK_ADMIN_SECRET_KEY: "<secret key>"
KEYCLOAK_ADMIN_REALM: "realm"

NOCODB_URL : "<url>"
NOCODB_TECH_LOGIN: 'USER'
NOCODB_TECH_PWD: 'PWD'
NOCODB_PROJECT:
  - PROJECT-1
  - PROJECT-2
