DEBUG: true

database:
  DB_HOST: localhost
  DB_PORT: '5432'
  DB_USER: postgres
  DB_PASSWORD: password
  DB_NAME: CHORUS

api:
  port: 5000

api_siren : http://152.228.212.208:443/v3/etablissements/

data:
  chorus: "C:\\Users\\jolivetspresta\\Documents\\projects\\SIBSGAR\\data\\ZBI_INF_BUD_53 TEST AE CC 2021.csv"